// <auto-generated />
using System;
using Artify.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Artify.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230819100432_database")]
#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
    partial class database
#pragma warning restore CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlbumShot", b =>
                {
                    b.Property<int>("AlbumsId")
                        .HasColumnType("int");

                    b.Property<int>("ShotsId")
                        .HasColumnType("int");

                    b.HasKey("AlbumsId", "ShotsId");

                    b.HasIndex("ShotsId");

                    b.ToTable("AlbumShot");
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Attributes.Appreciation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ShotId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShotId");

                    b.HasIndex("UserId");

                    b.ToTable("Appreciations");
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Attributes.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Attributes.ShotComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ShotId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShotId");

                    b.HasIndex("UserId");

                    b.ToTable("ShotComments");
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Attributes.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Attributes.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("money");

                    b.Property<int>("ShotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShotId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Shot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Shots");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.Billing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardCVV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CardExp")
                        .HasColumnType("datetime2");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Billings");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.Follower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.SocialProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SocialProfiles");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MemberUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberUserId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.UserEmployerComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("UserId");

                    b.ToTable("UserEmployerComments");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.UserSocialProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SocialProfileId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SocialProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSocialProfiles");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.Vacancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<bool>("InBest")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemoteAvailable")
                        .HasColumnType("int");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.UserDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InheritedRoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FinishYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartYear")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkPreferenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkPreferenceId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.FreelanceAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FixedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("money");

                    b.Property<int>("MinContractHours")
                        .HasColumnType("int");

                    b.Property<decimal>("MinHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("money");

                    b.Property<int>("WorkPreferenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkPreferenceId")
                        .IsUnique();

                    b.ToTable("FreelanceAvailabilities");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.FullTimeAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemoteAvailable")
                        .HasColumnType("int");

                    b.Property<int?>("SalaryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("WorkPreferenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalaryId");

                    b.HasIndex("WorkPreferenceId")
                        .IsUnique();

                    b.ToTable("FullTimeAvailabilities");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FinishYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("StartYear")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkPreferenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkPreferenceId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("money");

                    b.Property<decimal>("MinSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.WorkPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("WorkPreferences");
                });

            modelBuilder.Entity("BillingUser", b =>
                {
                    b.Property<int>("BillingsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("BillingsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("BillingUser");
                });

            modelBuilder.Entity("FollowerUser", b =>
                {
                    b.Property<int>("FollowersId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("FollowersId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("FollowerUser");
                });

            modelBuilder.Entity("GenreShot", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.Property<int>("ShotsId")
                        .HasColumnType("int");

                    b.HasKey("GenresId", "ShotsId");

                    b.HasIndex("ShotsId");

                    b.ToTable("GenreShot");
                });

            modelBuilder.Entity("PermissionUserRole", b =>
                {
                    b.Property<int>("PermissionsId")
                        .HasColumnType("int");

                    b.Property<int>("UserRolesId")
                        .HasColumnType("int");

                    b.HasKey("PermissionsId", "UserRolesId");

                    b.HasIndex("UserRolesId");

                    b.ToTable("PermissionUserRole");
                });

            modelBuilder.Entity("ProjectShot", b =>
                {
                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.Property<int>("ShotsId")
                        .HasColumnType("int");

                    b.HasKey("ProjectsId", "ShotsId");

                    b.HasIndex("ShotsId");

                    b.ToTable("ProjectShot");
                });

            modelBuilder.Entity("ShotTag", b =>
                {
                    b.Property<int>("ShotsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("ShotsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ShotTag");
                });

            modelBuilder.Entity("ShotTool", b =>
                {
                    b.Property<int>("ShotsId")
                        .HasColumnType("int");

                    b.Property<int>("ToolsId")
                        .HasColumnType("int");

                    b.HasKey("ShotsId", "ToolsId");

                    b.HasIndex("ToolsId");

                    b.ToTable("ShotTool");
                });

            modelBuilder.Entity("SpecialityWorkPreference", b =>
                {
                    b.Property<int>("SpecialitiesId")
                        .HasColumnType("int");

                    b.Property<int>("WorkPreferencesId")
                        .HasColumnType("int");

                    b.HasKey("SpecialitiesId", "WorkPreferencesId");

                    b.HasIndex("WorkPreferencesId");

                    b.ToTable("SpecialityWorkPreference");
                });

            modelBuilder.Entity("TeamTeamMember", b =>
                {
                    b.Property<int>("TeamMembersId")
                        .HasColumnType("int");

                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("TeamMembersId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("TeamTeamMember");
                });

            modelBuilder.Entity("AlbumShot", b =>
                {
                    b.HasOne("Artify.Models.DbModels.DbModels.Artworks.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.DbModels.Artworks.Shot", null)
                        .WithMany()
                        .HasForeignKey("ShotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Album", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.UserDTO", "UserDTO")
                        .WithMany("Albums")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDTO");
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Attributes.Appreciation", b =>
                {
                    b.HasOne("Artify.Models.DbModels.DbModels.Artworks.Shot", "Shot")
                        .WithMany("Appreciations")
                        .HasForeignKey("ShotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.Users.UserDTO", "Author")
                        .WithMany("Appreciations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Shot");
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Attributes.ShotComment", b =>
                {
                    b.HasOne("Artify.Models.DbModels.DbModels.Artworks.Shot", "Shot")
                        .WithMany("ShotComments")
                        .HasForeignKey("ShotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.Users.UserDTO", "Author")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Shot");
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Image", b =>
                {
                    b.HasOne("Artify.Models.DbModels.DbModels.Artworks.Shot", "Shot")
                        .WithMany("Images")
                        .HasForeignKey("ShotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shot");
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Project", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.UserDTO", "UserDTO")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDTO");
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Shot", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.UserDTO", "UserDTO")
                        .WithMany("Shots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDTO");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.Employer", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.UserDTO", "UserDTO")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDTO");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.TeamMember", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.UserDTO", "MemberUser")
                        .WithMany()
                        .HasForeignKey("MemberUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemberUser");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.UserEmployerComment", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.Attributes.Employer", "Employer")
                        .WithMany("UserEmployerComments")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.Users.UserDTO", "UserDTO")
                        .WithMany("UserEmployerComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("UserDTO");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.UserSocialProfile", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.Attributes.SocialProfile", "SocialProfile")
                        .WithMany("UserSocialProfiles")
                        .HasForeignKey("SocialProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.Users.UserDTO", "UserDTO")
                        .WithMany("UserSocialProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SocialProfile");

                    b.Navigation("UserDTO");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.Vacancy", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.Attributes.Employer", "Employer")
                        .WithMany("Vacancies")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.WorkPreferences.Speciality", "Speciality")
                        .WithMany("Vacancy")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Team", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.UserDTO", "UserDTO")
                        .WithMany("Teams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDTO");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.UserDTO", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.Education", b =>
                {
                    b.HasOne("Artify.Models.DbModels.WorkPreferences.WorkPreference", "WorkPreference")
                        .WithMany("Educations")
                        .HasForeignKey("WorkPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkPreference");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.FreelanceAvailability", b =>
                {
                    b.HasOne("Artify.Models.DbModels.WorkPreferences.WorkPreference", "WorkPreference")
                        .WithOne("FreelanceAvailability")
                        .HasForeignKey("Artify.Models.DbModels.WorkPreferences.FreelanceAvailability", "WorkPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkPreference");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.FullTimeAvailability", b =>
                {
                    b.HasOne("Artify.Models.DbModels.WorkPreferences.Salary", "Salary")
                        .WithMany("FullTimeAvailabilities")
                        .HasForeignKey("SalaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.WorkPreferences.WorkPreference", "WorkPreference")
                        .WithOne("FullTimeAvailability")
                        .HasForeignKey("Artify.Models.DbModels.WorkPreferences.FullTimeAvailability", "WorkPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salary");

                    b.Navigation("WorkPreference");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.Job", b =>
                {
                    b.HasOne("Artify.Models.DbModels.WorkPreferences.WorkPreference", "WorkPreference")
                        .WithMany("Jobs")
                        .HasForeignKey("WorkPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkPreference");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.WorkPreference", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.UserDTO", "UserDTO")
                        .WithOne("WorkPreference")
                        .HasForeignKey("Artify.Models.DbModels.WorkPreferences.WorkPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDTO");
                });

            modelBuilder.Entity("BillingUser", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.Attributes.Billing", null)
                        .WithMany()
                        .HasForeignKey("BillingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.Users.UserDTO", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FollowerUser", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.Attributes.Follower", null)
                        .WithMany()
                        .HasForeignKey("FollowersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.Users.UserDTO", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreShot", b =>
                {
                    b.HasOne("Artify.Models.DbModels.DbModels.Artworks.Attributes.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.DbModels.Artworks.Shot", null)
                        .WithMany()
                        .HasForeignKey("ShotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionUserRole", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.Users.UserRole", null)
                        .WithMany()
                        .HasForeignKey("UserRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectShot", b =>
                {
                    b.HasOne("Artify.Models.DbModels.DbModels.Artworks.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.DbModels.Artworks.Shot", null)
                        .WithMany()
                        .HasForeignKey("ShotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShotTag", b =>
                {
                    b.HasOne("Artify.Models.DbModels.DbModels.Artworks.Shot", null)
                        .WithMany()
                        .HasForeignKey("ShotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.DbModels.Artworks.Attributes.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShotTool", b =>
                {
                    b.HasOne("Artify.Models.DbModels.DbModels.Artworks.Shot", null)
                        .WithMany()
                        .HasForeignKey("ShotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.DbModels.Artworks.Attributes.Tool", null)
                        .WithMany()
                        .HasForeignKey("ToolsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecialityWorkPreference", b =>
                {
                    b.HasOne("Artify.Models.DbModels.WorkPreferences.Speciality", null)
                        .WithMany()
                        .HasForeignKey("SpecialitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.WorkPreferences.WorkPreference", null)
                        .WithMany()
                        .HasForeignKey("WorkPreferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamTeamMember", b =>
                {
                    b.HasOne("Artify.Models.DbModels.Users.Attributes.TeamMember", null)
                        .WithMany()
                        .HasForeignKey("TeamMembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artify.Models.DbModels.Users.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Artify.Models.DbModels.DbModels.Artworks.Shot", b =>
                {
                    b.Navigation("Appreciations");

                    b.Navigation("Images");

                    b.Navigation("ShotComments");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.Employer", b =>
                {
                    b.Navigation("UserEmployerComments");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.Attributes.SocialProfile", b =>
                {
                    b.Navigation("UserSocialProfiles");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.UserDTO", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Appreciations");

                    b.Navigation("Projects");

                    b.Navigation("Shots");

                    b.Navigation("Teams");

                    b.Navigation("UserEmployerComments");

                    b.Navigation("UserSocialProfiles");

                    b.Navigation("WorkPreference");
                });

            modelBuilder.Entity("Artify.Models.DbModels.Users.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.Salary", b =>
                {
                    b.Navigation("FullTimeAvailabilities");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.Speciality", b =>
                {
                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Artify.Models.DbModels.WorkPreferences.WorkPreference", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("FreelanceAvailability");

                    b.Navigation("FullTimeAvailability");

                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
